### ISSUE TITLE
All "N/A" ports, and no devices appearing in mate3_write --list-fields other than Mate

### ISSUE THREAD

**Issue by tymarbut** [adamcharnock/mate3#10]
Using the CLI commands, I got a message saying I should raise an issue in GitHub, so here I am.

I have a Mate3s with ~9 month old firmware, on a Hub10, 2x Radian GS8048a, 3x FM-100, and FNDC.  All data interfacing functions of the Mate seem to work normally.

I'm happy to send the entirety of what I see in the terminal, but it's pretty straightforward.  When I first run mate3_write ... --list-fields, it starts with 25 lines of the following:

`20200828 01:51:55 Unknown device type with device ID 120`

Then, it lists the mate3 and outback_system_control with "Hub ports" showing N/A, and all of the following fields show N/A for the ports.  There are no fields listed for any of the devices on the hub (inverters, charge controllers, FNDC).

`=================================== Devices ====================================`
`DEVICE NAME                         HUB PORT(S)`
`mate3                                    N/A`
`outback_system_control                   N/A`
`==================================== Fields ====================================`
`FIELD NAME                                                           HUB PORT(S)`
`mate3.ags_24_hour_start_mode                                         N/A          0=Disabled, 1=Enabled`
`mate3.ags_24_hour_start_voltage                                      N/A          Twenty Four Hour AGS Start Voltage`
`mate3.ags_2_hour_start_mode                                          N/A          0=Disabled, 1=Enabled`
`mate3.ags_2_hour_start_voltage                                       N/A          Two Hour AGS Start Voltage`

...etc.

Obviously, I can't write to the fields, and in trying to do so, I learned that I:

`Cannot set values for devices which lack a 'port_number' field. Please raise an issue in GitHub if you see this, including details of the device you are trying to set values on.`

My main goal is to be able to change the AC mode on the master inverter, although there are a number of Mate-related fields that would also be nice to be able to change.  Thanks for taking a look.

**Comment by kodonnell** [comment]
@tymarbut - I think this is supported in PR #6 . You're welcome to check it out and have a try - or, if you're willing to wait an indetermined-but-hopefully-not-too-long time, I'll push it to PyPI etc.

**Comment by kodonnell** [comment]
>if you're willing to wait an indetermined-but-hopefully-not-too-long time, I'll push it to PyPI etc.

Done = ) I haven't tested writing robustly, so be warned - but I figure it's best to push now. I'm planning on working more on this over the next month, including writing to the mate.

**Comment by kodonnell** [comment]
Closing as I think this should be covered in the most recent library, and I haven't heard otherwise. Feel free to reopen @tymarbut if that's not the case!
