### ISSUE TITLE
Developer docs

### ISSUE THREAD

**Issue by kodonnell** [adamcharnock/mate3#16]
Not urgent, but it'd be good to add some developer documentation that includes:

- Basics of modbus
- SunSpec (and how it differs to Outback etc.)
- Specifics of Outback spec e.g. the 'configuration' modules, etc.
- Description of the code and generally how it works. Even I'll admit it's a bit messy at the moment, including the auto-generated stuff. With models/values/devices/etc. nomenclature is a bit confusing.
-

**Comment by chinezbrun** [comment]
Fully agree. For a basic user, like me, I appreciate to have the last 2 bullet points as first priority !

**Comment by chinezbrun** [comment]
**Python examples**
I think will be good for beginning to enhance the python examples with more / all "hidden" capabilities of the API, including the expected output will helps to get in one shoot the potential without the need to play with python.
- examples of writing should be separate code to avoid any damage ( in my case i remarked them when i played with python example)
- then a list of mod Bus fields as were defined in API (i.e days_since_charge_parameters_met) will be good to have it clear somewhere how to get them. I found them in values.py but i searched a bit.

**Comment by kodonnell** [comment]
Kinda closed with #21 . More specific documentation requests probably make sense in a separate "doing docs better" issue, as we should probably discuss wider things like hosting pretty docs, etc. But not urgent for now.
