### ISSUE TITLE
mate3 command not installed (on Windows?)

### ISSUE THREAD

**Issue by chinezbrun** [adamcharnock/mate3#2]
I did not manage to use CLI as described ex mate3 -h. 
I used instead: 
python C:\Users\chine\Downloads\mate3-master\mate3-master\mate3\main.py --host 192.168.0.150 --format json
Maybe should be better explained.

**Comment by adamcharnock** [comment]
Hi @chinezbrun, ah I see. So I can better understand, can you tell me how you installed `mate3`?

**Comment by adamcharnock** [comment]
I've just taken a look at the readme and realised it lacked any installation information at all. I've added it now, which should hopefully be helpful to others. Thank you for pointing this out.

I'd still be interested to hear the answer to the above question :-)

**Comment by chinezbrun** [comment]
i used: pip install mate3
I was able to use the library and the example of the python code w/o any issue
The issue happened when i tried to run the CLI command from the power shell interface

**Comment by adamcharnock** [comment]
Hum, thank you. I'm testing this out on my machine (macOS) now:

```
# Creating a fresh virtualenv
$ mkdir test_mate3
$ cd test_mate3
$ pipenv local 3.8.1
$ touch Pipfile
$ pipenv install
$ pipenv shell

# Installing
$ pip install mate3
usage: mate3 [-h] --host HOST [--port PORT] [--format {text,prettyjson,json}]

Read all available data from the Mate3 controller

optional arguments:
  -h, --help            show this help message and exit
  --host HOST, -H HOST  The host name or IP address of the Mate3
  --port PORT, -p PORT  The port number address of the Mate3
  --format {text,prettyjson,json}, -f {text,prettyjson,json}
                        Output format
```

So it certainly seems to work on my side of things. However, it is possible that there is something that doesn't work on Windows. Unfortunately, if this is the case then I'm not really in a position to debug it.

I'm going to rename this issue to reflect this.

## Next steps

Things that will help move this issue forwards:

* Further reports of this issue (has this happened to you? Let me know!)
* A pull request from someone who's in a better position to debug this issue

Thank you again @chinezbrun for reporting this. I'm sorry I cannot do more right now.

**Comment by kodonnell** [comment]
Closing @chinezbrun as from other issues it sounds like you've got past this?
