### ISSUE TITLE
On write, fields are still marked as dirty

### ISSUE THREAD

**Issue by kodonnell** [adamcharnock/mate3#20]
Current behaviour after assigning a new value is for the old value to stay present, and the field marked as `dirty` with an internal `_value_to_write` variable holding the new value. Then, on `client.write()` the `_value_to_write` is written - but that's it, and it's still marked as `dirty` etc. 

I think this leaving as `dirty` was deliberate in that who knows what value is actually on the device until we re-read it - the write could have failed, etc. So, the idea was that after writing you should probably do a `client.read()` to get the new value. However, as it stands, there's no state indicating the three different scenarios:

- `read`: The value matches what's on the device, at the time of the read.
- `dirty: waiting to write`: We've assigned a new value but we haven't written it yet.
- `dirty: written but write unverified`: We've tried to write, but haven't read it to check. (When we do, it'll go back to the `read` state.)

The other option is (optionally) auto-committing (like a database) so as soon as you set a value it automatically writes the value and then re-reads it (and throws an error if the write didn't result in the correct value). This would probably be the safest in the sense of:

- Easiest to understand for newcomers - behaves as expected.
- Less likely to get into weird problems when you have multiple fields e.g. you write one field depending on another, but you forgot to write the former so it didn't use the `dirty` value you thought it would, etc.

The main downside is it'd be slower (?) for a large number of sequential writes. But that seems a pretty rare use case, so I'd be willing to ignore that for now. (And, if it becomes an issue, we could always implement `autocommit=False`.)

Any preferences @adamcharnock ? I don't imagine this is particularly high priority at the moment.

**Comment by adamcharnock** [comment]
Hey @kodonnell. No strong preference, except a general preference to keep things simple unless there is a compelling case otherwise. This leads me to have a bias towards your second proposed solution. But it's also almost 1am here, so feel free to try to convince me otherwise when I'm more awake :-)

**Comment by kodonnell** [comment]
> No strong preference, except a general preference to keep things simple unless there is a compelling case otherwise. This leads me to have a bias towards your second proposed solution.

Done - check out the new master, but the summary is that there's now `read` and `write` methods for every field.
