### ISSUE TITLE
[question] Performance Speed 

### ISSUE THREAD

**Issue by chinezbrun** [adamcharnock/mate3#30]
I interesting to know how long Mate3 modbus is busy when we'll do a read() -- full set of values
Did you perform any speed test?

**Comment by kodonnell** [comment]
I haven't, but `time mate3 read --host=... > /dev/null 2>&1` should give you what you need. The general rule-of-thumb info is mentioned [in the readme](https://github.com/adamcharnock/mate3/blob/6c378cc7d5eee59e322075b7fcdc91c49b24265f/README.md#modbus).

Feel free to post the results here, or maybe submit a PR with updated docs on mate performance?

**Comment by chinezbrun** [comment]
here it is
~~~
pi@raspberrypi:~ $ time mate3 read --host=192.168.0.150  > /dev/null 2>&1
real	0m0.741s
user	0m0.631s
sys	0m0.058s
pi@raspberrypi:~ $ time mate3 read --host=192.168.0.150  > /dev/null 2>&1
real	0m0.703s
user	0m0.594s
sys	0m0.081s
pi@raspberrypi:~ $ time mate3 read --host=192.168.0.150  > /dev/null 2>&1
real	0m0.716s
user	0m0.602s
sys	0m0.080s
pi@raspberrypi:~ $ time mate3 read --host=192.168.0.150  > /dev/null 2>&1
real	0m0.713s
user	0m0.587s
sys	0m0.092s
pi@raspberrypi:~ $ time mate3 read --host=192.168.0.150  > /dev/null 2>&1
real	0m0.727s
user	0m0.651s
sys	0m0.040s
pi@raspberrypi:~ $ 
~~~

**Comment by kodonnell** [comment]
Thanks @chinezbrun . I'll close this issue now, as I think your `time`s answers your question.
