### ISSUE TITLE
AttributeError: 'Mate3' object has no attribute 'get_device_blocks'

### ISSUE THREAD

**Issue by chinezbrun** [adamcharnock/mate3#5]
Tried to use the python3 like in the example provided and i get this error when tried to get all values for a specific device or specific value.

my code:
from mate3 import mate3_connection
from mate3.parsers import ChargeControllerParser, ChargeControllerConfigurationParser
from mate3.base_structures import Device

host = '192.168.0.150'
port = 502
with mate3_connection(host, port) as client:
    all_blocks = client.all_blocks()
    for block in all_blocks:
        print(block)
    values = client.get_device_blocks(Device.charge_controller)
    print(list(values))

**Comment by kodonnell** [comment]
Hey @chinezbrun - could you please wrap your code in code blocks and add indentation to make it easier to read, and post the full stack trace? Can you also confirm whether you have the latest version? As `get_device_blocks` does seem to exist currently: https://github.com/adamcharnock/mate3/blob/18e55d5568cc3b69c040e9e0271973fbc7432ba1/mate3/api.py#L89

**Comment by chinezbrun** [comment]
i checked and indeed i used old version. all ok now with latest one
Sorry for confusion.
