### ISSUE TITLE
Mate3Parser writing 

### ISSUE THREAD

**Issue by chinezbrun** [adamcharnock/mate3#7]
Tried to set value for Mate3 with:
  client.set_value(field=Mate3Parser.sched_3_ac_mode, value=4,  port=0)
As Mate3 do not have any port field, I put port=0 hoping that that will work...
Below the traceback of the error:

Traceback (most recent call last):
  File "C:\Users\chine\AppData\Local\Programs\Thonny\lib\site-packages\thonny\backend.py", line 1164, in _execute_prepared_user_code
    exec(statements, global_vars)
  File "S:\Development\Python_Scripts\Examples\Mate3_GitHubModule\mate3_Modbus_githubModule_write.py", line 24, in <module>
    client.set_value(field=Mate3Parser.sched_3_ac_mode,value=4, port=0)
  File "C:\Users\chine\AppData\Roaming\Python\Python37\site-packages\mate3\api.py", line 187, in set_value
    "Cannot set values for devices which lack a 'port_number' field. "
Exception: Cannot set values for devices which lack a 'port_number' field. Please raise an issue in GitHub if you see this, including details of the device you are trying to set values on.

**Comment by kodonnell** [comment]
Hi @chinezbrun it looks like you're using an old version of the code - I'm not sure if that's because Pypi hasn't been updated, or because of what you have installed. Either way, if you master, it looks like the latest code should work if you just don't give a port argument (or set it to `None`).

**Comment by chinezbrun** [comment]
i'm using version 0.4.0, just installed. I tested also on other computer - same result:

"Exception: Cannot set values for devices which lack a 'port_number' field. Please raise an issue in GitHub if you see this, including details of the device you are trying to set values on."

**Comment by kodonnell** [comment]
As above, you need to install from master. If you don't want to clone the repo, you can try

```
$ pip install git+https://github.com/adamcharnock/mate3.git
```

Fixing this happened in the last commit, but a new version wasn't pushed to Pypi. https://github.com/adamcharnock/mate3/commit/18e55d5568cc3b69c040e9e0271973fbc7432ba1

**Comment by chinezbrun** [comment]
Thanks. Installed from master -> ok
